/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Modelo.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author temaj
 */
public class GestionVentana extends javax.swing.JPanel {

    /**
     * Creates new form GestionVentana
     */
    private GestionEstudiantes gestion;
    
    public GestionVentana() {
        this.gestion = new GestionEstudiantes();
        initComponents();
        cargarDatosTabla();
    }
    
    public void cargarDatosTabla() {
        if (gestion == null || tablaRegistrados == null) return;

        DefaultTableModel model = (DefaultTableModel) tablaRegistrados.getModel();
        model.setRowCount(0);

        for (Estudiante e : gestion.getListaEstudiantes()) {
            model.addRow(new Object[]{
                e.getCarnet(),
                e.getNombre(),
                e.getApellido(),
                e.getEdad(),
                e.getCarrera()
            });
        }
    }

    private void limpiarFormulario() {
        textoCarne.setText("");
        textoNombre.setText("");
        textoApellido.setText("");
        textoEdad.setText("");
        textoCarrera.setText("");
        textoBuscarCarne.setText("");
        textoCarne.setEditable(true);
        if (tablaRegistrados != null) tablaRegistrados.clearSelection();
    }
    
    private void ejecutarBusqueda() {
        String carnetBusqueda = textoBuscarCarne.getText().trim();

        if (carnetBusqueda.isEmpty() || carnetBusqueda.equalsIgnoreCase("Buscar carné")) {
            JOptionPane.showMessageDialog(this, "Ingrese un carné para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Estudiante encontrado = gestion.buscarEstudiante(carnetBusqueda);

        if (encontrado != null) {
            // 1. Cargar datos en los campos de texto
            textoCarne.setText(encontrado.getCarnet());
            textoNombre.setText(encontrado.getNombre());
            textoApellido.setText(encontrado.getApellido());
            textoEdad.setText(String.valueOf(encontrado.getEdad()));
            textoCarrera.setText(encontrado.getCarrera());
            textoCarne.setEditable(false);

            // 2. Seleccionar la fila en la tabla
            DefaultTableModel model = (DefaultTableModel) tablaRegistrados.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).toString().equalsIgnoreCase(carnetBusqueda)) {
                    tablaRegistrados.setRowSelectionInterval(i, i);
                    tablaRegistrados.scrollRectToVisible(tablaRegistrados.getCellRect(i, 0, true));
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Estudiante no encontrado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        textoNombre = new javax.swing.JTextField();
        textoCarne = new javax.swing.JTextField();
        textoApellido = new javax.swing.JTextField();
        textoEdad = new javax.swing.JTextField();
        textoCarrera = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        textoBuscarCarne = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistrados = new javax.swing.JTable();
        btnCargarSeleccion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Apellido:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Carné:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Carrera:");

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        textoNombre.setBackground(new java.awt.Color(255, 255, 255));
        textoNombre.setForeground(new java.awt.Color(0, 0, 0));
        textoNombre.setText("Escribir nombre");
        textoNombre.addActionListener(this::textoNombreActionPerformed);

        textoCarne.setBackground(new java.awt.Color(255, 255, 255));
        textoCarne.setForeground(new java.awt.Color(0, 0, 0));
        textoCarne.setText("Escribir carné");
        textoCarne.addActionListener(this::textoCarneActionPerformed);

        textoApellido.setBackground(new java.awt.Color(255, 255, 255));
        textoApellido.setForeground(new java.awt.Color(0, 0, 0));
        textoApellido.setText("Escribir apellido");
        textoApellido.addActionListener(this::textoApellidoActionPerformed);

        textoEdad.setBackground(new java.awt.Color(255, 255, 255));
        textoEdad.setForeground(new java.awt.Color(0, 0, 0));
        textoEdad.setText("Escribir edad:");
        textoEdad.addActionListener(this::textoEdadActionPerformed);

        textoCarrera.setBackground(new java.awt.Color(255, 255, 255));
        textoCarrera.setForeground(new java.awt.Color(0, 0, 0));
        textoCarrera.setText("Escribir  carrera:");
        textoCarrera.addActionListener(this::textoCarreraActionPerformed);

        btnNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        textoBuscarCarne.setBackground(new java.awt.Color(255, 255, 255));
        textoBuscarCarne.setForeground(new java.awt.Color(0, 0, 0));
        textoBuscarCarne.setText("Buscar carné");
        textoBuscarCarne.addActionListener(this::textoBuscarCarneActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tablaRegistrados.setBackground(new java.awt.Color(255, 255, 255));
        tablaRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Carné", "Nombre", "Apellido", "Edad", "Carreral"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistrados);

        btnCargarSeleccion.setBackground(new java.awt.Color(0, 0, 0));
        btnCargarSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarSeleccion.setText("Cargar Selección");
        btnCargarSeleccion.addActionListener(this::btnCargarSeleccionActionPerformed);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Agregar Estudiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(textoBuscarCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCargarSeleccion)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addComponent(jScrollPane1))
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(textoBuscarCarne))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCargarSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(121, 121, 121))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
        String carnet = textoCarne.getText().trim();
        String nombre = textoNombre.getText().trim();
        String apellido = textoApellido.getText().trim();
        String edadTexto = textoEdad.getText().trim();
        String carrera = textoCarrera.getText().trim();

        if (carnet.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || edadTexto.isEmpty() || carrera.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int edad = Integer.parseInt(edadTexto);

        // Verifica si el estudiante ya existe
        Modelo.Estudiante existente = gestion.buscarEstudiante(carnet);
        if (existente == null) {
            Modelo.Estudiante nuevo = new Modelo.Estudiante(carnet, nombre, apellido, edad, carrera);
            gestion.agregarEstudiante(nuevo);
            javax.swing.JOptionPane.showMessageDialog(this, "Estudiante guardado exitosamente.");
        } else {
            existente.setNombre(nombre);
            existente.setApellido(apellido);
            existente.setEdad(edad);
            existente.setCarrera(carrera);
            javax.swing.JOptionPane.showMessageDialog(this, "Estudiante actualizado exitosamente.");
        }

        cargarDatosTabla();
        limpiarFormulario();

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un número entero válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCarneActionPerformed

    private void textoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApellidoActionPerformed

    private void textoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEdadActionPerformed

    private void textoCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCarreraActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void textoBuscarCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBuscarCarneActionPerformed
        // TODO add your handling code here:
        ejecutarBusqueda();
        
    }//GEN-LAST:event_textoBuscarCarneActionPerformed

    private void btnCargarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarSeleccionActionPerformed
        // TODO add your handling code here:
        int fila = tablaRegistrados.getSelectedRow();

    if (fila >= 0) {
        textoCarne.setText(tablaRegistrados.getValueAt(fila, 0).toString());
        textoNombre.setText(tablaRegistrados.getValueAt(fila, 1).toString());
        textoApellido.setText(tablaRegistrados.getValueAt(fila, 2).toString());
        textoEdad.setText(tablaRegistrados.getValueAt(fila, 3).toString());
        textoCarrera.setText(tablaRegistrados.getValueAt(fila, 4).toString());
        textoCarne.setEditable(false);
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una fila de la tabla primero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
        
    }//GEN-LAST:event_btnCargarSeleccionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String carnetELiminar = "";
    int fila = tablaRegistrados.getSelectedRow();

    if (fila >= 0) {
        carnetELiminar = tablaRegistrados.getValueAt(fila, 0).toString();
    } else {
        carnetELiminar = textoCarne.getText().trim();
    }

    if (carnetELiminar.isEmpty() || carnetELiminar.equalsIgnoreCase("Escribir carné")) {
        JOptionPane.showMessageDialog(this, "Seleccione un registro o ingrese un carné para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro de eliminar al estudiante con carné " + carnetELiminar + "?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        boolean eliminado = gestion.eliminarEstudiante(carnetELiminar);
        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Estudiante eliminado correctamente.");
            cargarDatosTabla();
            limpiarFormulario();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el estudiante a eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ejecutarBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarSeleccion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegistrados;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JTextField textoBuscarCarne;
    private javax.swing.JTextField textoCarne;
    private javax.swing.JTextField textoCarrera;
    private javax.swing.JTextField textoEdad;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
